### ISSUE TITLE
error when running ODUSSEAS.py

### ISSUE THREAD

**Issue by sousasag** [AlexandrosAntoniadis/ODUSSEAS#4]
```
Area of line: 59.93mÅ
Area of line: 3.64mÅ
Area of line: 36.38mÅ
Area of line: 63.85mÅ
Area of line: 41.72mÅ
spectra/newstars/FEROS_Gl674final.fits
Traceback (most recent call last):
  File "ODUSSEAS.py", line 21, in <module>
    MachineLearning.ML(regression)
  File "/mnt/e/Linux_stuff/Programas/GIT_Projects/Others/ODUSSEAS/MachineLearning.py", line 80, in ML
    zeroews = newdf.mask(newdf<0.00001)
  File "/home/sousasag/Programas/anaconda3/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 788, in f
    new_data = dispatch_to_series(self, other, op)
  File "/home/sousasag/Programas/anaconda3/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 378, in dispatch_to_series
    bm = left._data.apply(array_op, right=right)
  File "/home/sousasag/Programas/anaconda3/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 440, in apply
    applied = b.apply(f, **kwargs)
  File "/home/sousasag/Programas/anaconda3/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 390, in apply
    result = func(self.values, **kwargs)
  File "/home/sousasag/Programas/anaconda3/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 247, in comparison_op
    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)
  File "/home/sousasag/Programas/anaconda3/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 57, in comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x.ravel(), y, op)
  File "pandas/_libs/ops.pyx", line 96, in pandas._libs.ops.scalar_compare
TypeError: '<' not supported between instances of 'str' and 'float'
```

**Comment by AlexandrosAntoniadis** [comment]
This error can be solved with installing the pandas version 0.20, as mentioned in the Installation Requirements at README.
